### ISSUE TITLE
Confusion on method naming

### ISSUE THREAD

**Issue by IshanArya** [Russell-Newton/DuckyLighting#1]
Hey, not an actual issue. But I wanted to know if this is a program I need to keep running in the background for my color schemes to show up or if I can just run it once and the color scheme will be saved on the keyboard.

Thanks!

**Comment by Russell-Newton** [comment]
Unfortunately, I do not know if it's possible to save something to the keyboard. This program is based on how Razer Chroma Connect interfaces with the default Ducky software: it continuously tells the keyboard how to light up each key, so it needs to stay running, just like the Chroma Connect and DuckyRGB would. You could have this made as a background task though so that you don't have to see it when it runs and it opens on startup. Important to note is that the DuckyRGB **CANNOT** be running when you start this code, it will not connect to the keyboard.

I believe the ducky firmware restricts you to only one of the preset layer types, which aren't great.
